### PR TITLE
Upgrade Dependencies

### PR DESCRIPTION
**Pull request by leonardoventurini**
- Upgrade all dependencies.
- Remove sub-steps from the table of contents.
- Make sure all tests pass.

> Note: I started using Jest's snapshot system for the deterministic tests (which everything should be?) please review the snapshots, as I could not find anything wrong with them by comparing with the original dump files. It seems like the "Begin tutorial" navigation bar at the bottom was added later nd it broke some of the tests...

image

### CODE REVIEW

**Comment by DAB0mB** [comment]
Why did you decide to remove sub-steps from TOC?

**Comment by leonardoventurini** [comment]
> Why did you decide to remove sub-steps from TOC?

I talked with the other guys working on the tutorials, and we decided it would not be necessary @DAB0mB and it would eliminate the complexity entailing it.

**Comment by DAB0mB** [comment]
@leonardoventurini sounds good. Also snapshots look alright, there are 15 skipped tests, why is that? its been a while since I ran the project, just wanna make sure

**Comment by leonardoventurini** [comment]
> @leonardoventurini sounds good. Also snapshots look alright, there are 15 skipped tests, why is that? its been a while since I ran the project, just wanna make sure

I don't know, honestly, they were already skipped... so I avoided messing with them for the time being as my schedule is already tight. I can take a look in the future, but I can't guarantee when, since I have some stuff come up for the following weeks. :thinking:

**Comment by DAB0mB** [comment]
Nice!

**Pull request merged**
