### PR TITLE
ES6ify

### PR DESCRIPTION
**Pull request by srtucker22**
Hey, so I've been running into challenges while running tortilla and thought it would make sense to upgrade the codebase to the latest JS to make finding issues and building enhancements a little easier. I also think other contributors will have an easier time understanding and contributing to the codebase with ES6 syntax. All the same tests seem to pass/fail for me with the latest changes.

Let me know whats good!

### CODE REVIEW

**Comment by DAB0mB** [comment]
I will test it myself and once I approve it I will merge it as well :-)

**Comment by DAB0mB** [comment]
@srtucker22 Looks good overall and all 101 tests pass on my machine. Just fix all the in-lines conditions e.g. [this one](https://github.com/Urigo/tortilla/pull/36/files#diff-3205b0a8091f28daa638a56a9d0d372bR101) and be sure to use a `class` in the [LocalCache module](https://github.com/srtucker22/tortilla/blob/master/src/local-cache.js).

**Comment by DAB0mB** [comment]
By the way if not all tests pass on your machine, well they should. So before continuing I suggest you start from there. If it works only on my machine it's basically useless...

**Comment by srtucker22** [comment]
Nearly all the tests pass except towards the end they start timing out on my machine

Otherwise, I get the following failed tests on the current version of `tortilla` as well as this PR:
```
1) Template Helpers diffStep should render a renamed file:

      Expected file to have the same content as 'rename-file.md'
      + expected - actual

       [{]: <helper> (diffStep 1.2)

       #### Step 1.2: Rename file

      -##### Changed test-file.js
      +##### Added new-test-file.js
      +```diff
      +@@ -0,0 +1,3 @@
      ++┊ ┊1┊foo
      ++┊ ┊2┊bar
      ++┊ ┊3┊baz🚫↵
      +```

      +##### Deleted test-file.js
      +```diff
      +@@ -1,3 +0,0 @@
      +-┊1┊ ┊foo
      +-┊2┊ ┊bar
      +-┊3┊ ┊baz🚫↵
      +```

       [}]: #

      at Function.<anonymous> (tests/assertions.js:42:35)
      at Function.ctx.(anonymous function) [as file] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (tests/template-helpers-test.js:41:28)

  2) Template Helpers diffStep translations should render a renamed file:

      Expected file to have the same content as 'he/rename-file.md'
      + expected - actual

       [{]: <helper> (diffStep 1.2)

       #### צעד 1.2: שינוי שם קובץ

      -##### שינינו את test-file.js
      +##### הוספנו את new-test-file.js
      +```diff
      +@@ -0,0 +1,3 @@
      ++┊ ┊1┊foo
      ++┊ ┊2┊bar
      ++┊ ┊3┊baz🚫↵
      +```

      +##### מחקנו את test-file.js
      +```diff
      +@@ -1,3 +0,0 @@
      +-┊1┊ ┊foo
      +-┊2┊ ┊bar
      +-┊3┊ ┊baz🚫↵
      +```

       [}]: #
```

Made the changes you requested. If I have a sec, I can go back and figure out why those 2 tests are failing, but I think this should hopefully be mergeable.

**Comment by srtucker22** [comment]
Also, other tests were breaking because of #23 but works with the latest Git (2.13.0)

**Pull request merged**
